<?php

namespace Taz\AutoTraderStockClient\DTOs;

use Spatie\DataTransferObject\DataTransferObject;

class VehicleDTO extends DataTransferObject
{
    public ?string $ownershipCondition;
    public ?string $registration;
    public ?string $vin;
    public ?string $make;
    public ?string $model;
    public ?string $generation;
    public ?string $derivative;
    public ?string $derivativeId;
    public ?string $vehicleType;
    public ?string $trim;
    public ?string $bodyType;
    public ?string $fuelType;
    public ?string $cabType;
    public ?string $transmissionType;
    public ?string $wheelbaseType;
    public ?string $roofHeightType;
    public ?string $drivetrain;
    public ?int $seats;
    public ?int $doors;
    public ?int $cylinders;
    public ?int $valves;
    public ?int $engineTorqueNM;
    public ?int $co2EmissionGPKM;
    public ?int $topSpeedMPH;
    public ?float $zeroToSixtyMPHSeconds;
    public ?float $zeroToOneHundredKMPHSeconds;
    public ?float $badgeEngineSizeLitres;
    public ?int $engineCapacityCC;
    public ?int $enginePowerBHP;
    public ?float $fuelCapacityLitres;
    public ?string $emissionClass;
    public ?int $owners;
    public ?float $fuelEconomyNEDCExtraUrbanMPG;
    public ?float $fuelEconomyNEDCUrbanMPG;
    public ?float $fuelEconomyNEDCCombinedMPG;
    public ?string $fuelEconomyWLTPLowMPG;
    public ?string $fuelEconomyWLTPMediumMPG;
    public ?string $fuelEconomyWLTPHighMPG;
    public ?string $fuelEconomyWLTPExtraHighMPG;
    public ?string $fuelEconomyWLTPCombinedMPG;
    public ?float $bootSpaceSeatsUpLitres;
    public ?string $insuranceGroup;
    public ?string $insuranceSecurityCode;
    public ?string $firstRegistrationDate;
    public ?string $colour;
    public ?string $style;
    public ?string $subStyle;
    public ?int $lengthMM;
    public ?int $heightMM;
    public ?int $widthMM;
    public ?int $payloadLengthMM;
    public ?int $payloadWidthMM;
    public ?int $payloadHeightMM;
    public ?int $payloadWeightKG;
    public ?int $minimumKerbWeightKG;
    public ?int $grossVehicleWeightKG;
    public ?string $engineNumber;
    public ?string $fuelDelivery;
    public ?int $gears;
    public ?bool $startStop;
    public ?int $enginePowerPS;
    public ?float $engineTorqueLBFT;
    public ?float $bootSpaceSeatsDownLitres;
    public ?int $batteryChargeTime;
    public ?int $batteryQuickChargeTime;
    public ?int $batteryRangeMiles;
    public ?int $batteryCapacityKWH;
    public ?int $batteryUsableCapacityKWH;
    public ?int $wheelbaseMM;
    public ?int $grossCombinedWeightKG;
    public ?int $grossTrainWeightKG;
    public ?int $boreMM;
    public ?int $strokeMM;
    public ?string $cylinderArrangement;
    public ?string $engineMake;
    public ?string $valveGear;
    public ?int $axles;
    public ?string $countryOfOrigin;
    public ?string $driveType;
    public ?string $payloadVolumeCubicMetres;
    public ?bool $rde2Compliant;
    public ?string $sector;
    public OemDTO $oem;
    public ?CollectionOfFeatures $features;
}
