<?php

namespace Avant\AutotraderStockClient\DTOs;

use Spatie\DataTransferObject\DataTransferObject;

class VehicleDTO extends DataTransferObject
{
    public ?string $ownershipCondition;
    public ?string $registration;
    public ?string $vin;
    public ?string $make;
    public ?string $model;
    public ?string $generation;
    public ?string $derivative;
    public ?string $derivativeId;
    public ?string $vehicleType;
    public ?string $trim;
    public ?string $bodyType;
    public ?string $fuelType;
    public ?string $cabType;
    public ?string $transmissionType;
    public ?string $wheelbaseType;
    public ?string $roofHeightType;
    public ?string $drivetrain;
    public ?string $seats;
    public ?string $doors;
    public ?string $cylinders;
    public ?string $valves;
    public ?string $engineTorqueNM;
    public ?string $co2EmissionGPKM;
    public ?string $topSpeedMPH;
    public ?string $zeroToSixtyMPHSeconds;
    public ?string $zeroToOneHundredKMPHSeconds;
    public ?string $badgeEngineSizeLitres;
    public ?string $engineCapacityCC;
    public ?string $enginePowerBHP;
    public ?string $fuelCapacityLitres;
    public ?string $emissionClass;
    public ?string $owners;
    public ?string $fuelEconomyNEDCExtraUrbanMPG;
    public ?string $fuelEconomyNEDCUrbanMPG;
    public ?string $fuelEconomyNEDCCombinedMPG;
    public ?string $fuelEconomyWLTPLowMPG;
    public ?string $fuelEconomyWLTPMediumMPG;
    public ?string $fuelEconomyWLTPHighMPG;
    public ?string $fuelEconomyWLTPExtraHighMPG;
    public ?string $fuelEconomyWLTPCombinedMPG;
    public ?string $bootSpaceSeatsUpLitres;
    public ?string $insuranceGroup;
    public ?string $insuranceSecurityCode;
    public ?string $firstRegistrationDate;
    public ?string $colour;
    public ?string $style;
    public ?string $subStyle;
    public ?string $lengthMM;
    public ?string $heightMM;
    public ?string $widthMM;
    public ?string $payloadLengthMM;
    public ?string $payloadWidthMM;
    public ?string $payloadHeightMM;
    public ?string $payloadWeightKG;
    public ?string $minimumKerbWeightKG;
    public ?string $grossVehicleWeightKG;
    public ?string $engineNumber;
    public ?string $fuelDelivery;
    public ?string $gears;
    public ?string $startStop;
    public ?string $enginePowerPS;
    public ?string $engineTorqueLBFT;
    public ?string $bootSpaceSeatsDownLitres;
    public ?string $batteryChargeTime;
    public ?string $batteryQuickChargeTime;
    public ?string $batteryRangeMiles;
    public ?string $batteryCapacityKWH;
    public ?string $batteryUsableCapacityKWH;
    public ?string $wheelbaseMM;
    public ?string $grossCombinedWeightKG;
    public ?string $grossTrainWeightKG;
    public ?string $boreMM;
    public ?string $strokeMM;
    public ?string $cylinderArrangement;
    public ?string $engineMake;
    public ?string $valveGear;
    public ?string $axles;
    public ?string $countryOfOrigin;
    public ?string $driveType;
    public ?string $payloadVolumeCubicMetres;
    public ?string $rde2Compliant;
    public ?string $sector;
    public OemDTO $oem;
    public CollectionOfFeatures $features;
}
